//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEscritorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoriaProducto
    {
        public CategoriaProducto()
        {
            this.Producto = new HashSet<Producto>();
            this.Producto1 = new HashSet<Producto>();
        }
    
        public long Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<Producto> Producto { get; set; }
        public virtual ICollection<Producto> Producto1 { get; set; }
    }
}
