//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEscritorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Factura = new HashSet<Factura>();
        }
    
        public long Id { get; set; }
        public string ApellidoYNombre { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string Documento { get; set; }
        public string CUIT { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public Nullable<long> IVAId { get; set; }
        public Nullable<long> TipoClienteId { get; set; }
    
        public virtual TipoCliente TipoCliente { get; set; }
        public virtual IVA IVA { get; set; }
        public virtual ICollection<Factura> Factura { get; set; }
    }
}
