//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEscritorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public long Id { get; set; }
        public Nullable<long> NumeroFactura { get; set; }
        public string TipoFactura { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<long> ClienteId { get; set; }
        public Nullable<long> ModoPagoId { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ModoPago ModoPago { get; set; }
    }
}
