//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEscritorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public long Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<int> Stock { get; set; }
        public Nullable<long> CategoriaId { get; set; }
        public Nullable<long> ProveedorId { get; set; }
        public Nullable<decimal> Precio2 { get; set; }
        public Nullable<decimal> Precio3 { get; set; }
        public Nullable<decimal> Costo { get; set; }
        public Nullable<int> Minimo { get; set; }
        public Nullable<int> Maximo { get; set; }
        public Nullable<long> CodigoBarra { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
    
        public virtual CategoriaProducto CategoriaProducto { get; set; }
        public virtual CategoriaProducto CategoriaProducto1 { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
