//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FacturacionEscritorio.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendedor
    {
        public long Id { get; set; }
        public string ApellidoYNombre { get; set; }
        public string Direccion { get; set; }
        public string Localidad { get; set; }
        public string Provincia { get; set; }
        public string Documento { get; set; }
        public string Telefono { get; set; }
        public string Email { get; set; }
        public long TipoVendedorId { get; set; }
    
        public virtual TipoVendedor TipoVendedor { get; set; }
    }
}
